version: 2

updates:
  - package-ecosystem: nuget
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: '08:00'
      timezone: Europe/Moscow
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - dotnet
    groups:
      dotnet-dependencies:
        patterns:
          - '*'

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: '08:30'
      timezone: Europe/Moscow
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - github-actions
    groups:
      github-actions:
        patterns:
          - '*'
